import type {Metadata} from "next";
import "./globals.css";
import {Jura} from 'next/font/google';
import Footer from "@/app/ui/Footer";
import NavLinks from '@/app/ui/NavLinks';

const jura = Jura({subsets: ['latin', 'cyrillic']});


export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
        <body
            className={`${jura.className} antialiased bg-[url('../public/keyboard.jpg')] bg-cover text-gray-200`}
        >
        <NavLinks/>
        {children}
        <Footer/>
        </body>
        </html>
    );
}
