import type { Metadata } from "next";
import "./globals.css";
import {Inter, Lusitana} from 'next/font/google';


const inter = Inter({ subsets: ['latin'] });

const lusitana = Lusitana({
  weight: ['400', '700'],
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} ${lusitana.className} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
