INSERT INTO public.artist (id, name, biography, name_ru, biography_ru, profession, admin_path, profession_ru)
VALUES (true, 'Alexander Kudryavtsev',
        'Alexander was born on July 31, 1987 in Moscow, Russia.' ||
        'He studied in Prof. T. Zelikman''s piano class at the Gnessin School and afterwards at the Gnessin Academy. Later he taught at the Gnessin Academy (2016 — 2022). Now he works as a teacher at the Kyrgyz National Conservatory named K. Maldybasanov.' ||
        'Alexander toured Italy, Germany, the Netherlands, the Czech Republic, France, and Russia as a pianist. Repeatedly performed solo and played with the orchestra in various halls of Moscow, including the Great Hall of the Moscow Conservatory. Have records on the radio and CDs.' ||
        'Alexander is the winner of many competitions. Among them is the 1st prize in the radio competition "Concertino Prague" (2003), the 1st prize and the medal of the President of Italy of the 4th international competition of the association "Dino Ciani" (Verbania, Italy, 2005), the winner of the 1st prize of the 1st Stanislav Neuhaus International Piano Competition (2007).',
        'Александр Кудрявцев',
        'Александр родился 31 июля 1987 года в Москве, Россия.' ||
        'Он учился в классе фортепиано профессора Т. А. Зеликман в Московской Средней Специальной Школе им. Гнесиных, а затем - в Академии им. Гнесиных. После учёбы Александр преподавал в Академии специальное фортепиано с 2016 по 2022 гг. В настоящее время Александр ведёт класс специального фортепиано в Кыргизской национальной консерватории имени К. Малдыбасанова.' ||
        'Александр гастролировал в Италии, Германии, Нидерландах, Чехии, Франции и России. Неоднократно выступал сольно и с оркестром в различных залах Москвы, в том числе в Большом зале Московской консерватории. Имеет записи на радио и компакт-дисках.' ||
        'Александр является лауреатом многих конкурсов. Среди них — 1-я премия радиоконкурса «Концертино Прага» (2003), 1-я премия и медаль Президента Италии 4-го международного конкурса ассоциации «Дино Чиани» (Вербания, Италия, 2005), 1-я премия 1-го Международного конкурса пианистов имени Станислава Нейгауза (2007).',
        'piano', 'admin', 'фортепиано');